package com.example.Netflix.NetflixClone.Model;

import javax.persistence.*;

//The @Entity annotation lets Hibernate know that we want to map this class to a database table.
@Entity
//The @Table annotation tells Hibernate the name of the table we want to map to.
@Table(name = "users")
public class User {

    //Each database table will have a primary key, and we tell hibernate which property we want it to use for the primary key by using the @Id annotation. We are going to use the idproperty.
    //We are also going to tell it to generate the value for the id primary key using the IDENTITY strategy. This uses an auto-incremented value generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "second_name")
    private String secondName;

    @Column(name = "age")
    private int age;

    public User(String firstName, String secondName, int age) {
        this.firstName = firstName;
        this.secondName = secondName;
        this.age = age;
    }

    public User() {

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSecondName() {
        return secondName;
    }

    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
